input {
  http {
    port => 5044
    tags => ["auth"]
  }
  http {
    port => 5045
    tags => ["game-store"]
  }
  http {
    port => 5046
    tags => ["gateway"]
  }
}

filter {
  if "auth" in [tags] {
    json {
      source => "message"
    }
    mutate {
      add_field => { "service" => "auth" }
    }
  }
  if "game-store" in [tags] {
    json {
      source => "message"
    }
    mutate {
      add_field => { "service" => "game-store" }
    }
  }
  if "gateway" in [tags] {
    json {
      source => "message"
    }
    mutate {
      add_field => { "service" => "gateway" }
    }
  }
}

output {
  if "auth" in [tags] {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "auth-service-logs-%{+YYYY.MM.dd}"
    }
  }
  if "game-store" in [tags] {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "game-store-service-logs-%{+YYYY.MM.dd}"
    }
  }
  if "gateway" in [tags] {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "gateway-logs-%{+YYYY.MM.dd}"
    }
  }
  stdout {
    codec => rubydebug
  }
}