input {
  beats {
    port => 5044
  }

  http {
    port => 6000
    codec => json_lines
  }

  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}