services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "3000:3000"
      - "50051:50051"
    depends_on:
      - auth-service
      - game-store-service-1
      - game-store-service-2
      - game-store-service-3
      - consul
      - logstash
    env_file:
      - ./gateway/.env 

  # Auth    
  auth-service:
    build: ./auth-service
    depends_on:
      - auth-db
    env_file:
      - ./auth-service/.env  
    deploy:
      replicas: 3
      
  auth-db:
    build: ./auth-service/src/db
    env_file:
      - ./auth-service/.env
    ports:
      - "5433:5432"
    volumes: 
      - auth_db_data:/var/lib/postgresql/data

  # Game Store
  game-store-service-1:
    build: ./game-store-service
    container_name: pad-labs-game-store-service-1
    depends_on:
      - game-db
      - redis-leader-1
      - redis-leader-2
      - redis-leader-3
    env_file:
      - ./game-store-service/.env  
    environment:
      - REDIS_HOST=redis-leader-1  
      - REDIS_PORT=6379  
    ports:
      - "5001:5001" 
  
  game-store-service-2:
    build: ./game-store-service
    container_name: pad-labs-game-store-service-2
    depends_on:
      - game-db
      - redis-leader-1
      - redis-leader-2
      - redis-leader-3
    env_file:
      - ./game-store-service/.env    
    environment:
      - REDIS_HOST=redis-leader-2  
      - REDIS_PORT=6379
    ports:
      - "5002:5001"        

  game-store-service-3:
    build: ./game-store-service
    container_name: pad-labs-game-store-service-3
    depends_on:
      - game-db
      - redis-leader-1
      - redis-leader-2
      - redis-leader-3
    env_file:
      - ./game-store-service/.env  
    environment:
      - REDIS_HOST=redis-leader-3    
      - REDIS_PORT=6379
    ports:
      - "5003:5001" 

  game-db:
    build: ./game-store-service/src/db
    env_file:
      - ./game-store-service/.env
    ports:
      - "5434:5432"  
    volumes:
      - game_db_data:/var/lib/postgresql/data

  # Service discovery
  consul:
    build:
      context: ./service-discovery
    container_name: consul  
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"

  # Redis
  redis-leader-1:
    image: redis:latest
    container_name: game-store-redis-leader-1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf

  redis-leader-2:
    image: redis:latest
    container_name: game-store-redis-leader-2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - 6380:6379
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf

  redis-leader-3:
    image: redis:latest
    container_name: game-store-redis-leader-3
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - 6381:6379
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf

  redis-follower-1:
    image: redis:latest
    container_name: game-store-redis-follower-1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - 6382:6379
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf

  redis-follower-2:
    image: redis:latest
    container_name: game-store-redis-follower-2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - 6383:6379
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf

  redis-follower-3:
    image: redis:latest
    container_name: game-store-redis-follower-3
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - 6384:6379
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf

  redis-cluster:
    image: redis:latest
    restart: no
    command: ["/bin/sh", "-c", "redis-cli --cluster create game-store-redis-leader-1:6379 game-store-redis-leader-2:6379 game-store-redis-leader-3:6379 game-store-redis-follower-1:6379 game-store-redis-follower-2:6379 game-store-redis-follower-3:6379 --cluster-replicas 1 --cluster-yes"]
    depends_on:
      - redis-leader-1
      - redis-leader-2
      - redis-leader-3    

  # ELK stack services
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data  

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash
    volumes:
      - ./configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ls_data:/usr/share/logstash/data
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch    

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    volumes:
      - kb_data:/usr/share/kibana/data
    ports:
      - "5601:5601" 
    depends_on:
      - elasticsearch

volumes:
  auth_db_data:
  game_db_data:
  es_data:
  ls_data:
  kb_data: