services:
  auth-service:
    build: ./auth-service
    ports:
      - "5001:5000"
    depends_on:
      - auth-db
    env_file:
      - ./auth-service/.env  
  auth-db:
    image: postgres:16
    env_file:
      - ./auth-service/.env
    ports:
      - "5432:5432"
    volumes:
      - ./auth-service/src/db:/docker-entrypoint-initdb.d  
  # gateway:
  #   build: ./gateway
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - auth-service
  #     - game-store-service
  # game-store-service:
  #   build: ./game-store-service
  #   ports:
  #     - "5002:5002"
  #   depends_on:
  #     - game-db
  # game-db:
  #   build: ./game-store-service/db
  #   ports:
  #     - "5433:5432"

  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"

  # service-discovery:
  #   image: consul
  #   ports:
  #     - "8500:8500"
