# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import game_store_pb2 as game__store__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in game_store_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuyGame = channel.unary_unary(
                '/game_store.GameStore/BuyGame',
                request_serializer=game__store__pb2.BuyGameRequest.SerializeToString,
                response_deserializer=game__store__pb2.BuyGameResponse.FromString,
                _registered_method=True)


class GameStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BuyGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuyGame': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyGame,
                    request_deserializer=game__store__pb2.BuyGameRequest.FromString,
                    response_serializer=game__store__pb2.BuyGameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game_store.GameStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('game_store.GameStore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BuyGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_store.GameStore/BuyGame',
            game__store__pb2.BuyGameRequest.SerializeToString,
            game__store__pb2.BuyGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
