# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game_store.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'game_store.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10game_store.proto\x12\ngame_store\"6\n\x0e\x42uyGameRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\ngame_title\x18\x02 \x01(\t\"7\n\x0f\x42uyGameResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x32O\n\tGameStore\x12\x42\n\x07\x42uyGame\x12\x1a.game_store.BuyGameRequest\x1a\x1b.game_store.BuyGameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUYGAMEREQUEST']._serialized_start=32
  _globals['_BUYGAMEREQUEST']._serialized_end=86
  _globals['_BUYGAMERESPONSE']._serialized_start=88
  _globals['_BUYGAMERESPONSE']._serialized_end=143
  _globals['_GAMESTORE']._serialized_start=145
  _globals['_GAMESTORE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
